DROP TABLE XXVS.SM_ENVIRONMENTS CASCADE CONSTRAINTS;
DROP TABLE XXVS.SM_COMP_OBJECTS CASCADE CONSTRAINTS;
DROP TABLE XXVS.SM_COMPONENTS CASCADE CONSTRAINTS;
DROP TABLE XXVS.SM_OBJECTS CASCADE CONSTRAINTS;
DROP TABLE XXVS.OA_MENU_ITEMS CASCADE CONSTRAINTS;
DROP TABLE XXVS.OA_MENUS CASCADE CONSTRAINTS;
DROP TABLE XXVS.SYS_MAPPINGS CASCADE CONSTRAINTS;
DROP TABLE XXVS.SYS_LISTS CASCADE CONSTRAINTS;
DROP TABLE XXVS.SYS_LIST_VALUES CASCADE CONSTRAINTS;
DROP TABLE XXVS.XXOA_DEBUG CASCADE CONSTRAINTS;

CREATE TABLE XXVS.XXOA_DEBUG
(
  MSG_ID  NUMBER,
  MSG     VARCHAR2(3000 BYTE)
);

CREATE TABLE XXVS.OA_MENUS
(
  ID           NUMBER                           NOT NULL PRIMARY KEY ,
  NAME         VARCHAR2(50 BYTE),
  DESCRIPTION  VARCHAR2(300 BYTE)
);

CREATE TABLE XXVS.OA_MENU_ITEMS
(
  ID           NUMBER                           NOT NULL PRIMARY KEY ,
  NAME         VARCHAR2(50 BYTE),
  PROMPT       VARCHAR2(300 BYTE),
  TARGET_TYPE  VARCHAR2(50 BYTE),
  TARGET       VARCHAR2(300 BYTE),
  MENU_ID      NUMBER
);
CREATE TABLE XXVS.SM_COMPONENTS
(
  ID              NUMBER                        NOT NULL PRIMARY KEY,
  NAME            VARCHAR2(300 BYTE)             NOT NULL,
  MODULE          VARCHAR2(20 BYTE),
  TRACK           VARCHAR2(20 BYTE),
  DESCRIPTION     VARCHAR2(250 BYTE),
  SM_STAGE        VARCHAR2(40 BYTE),
  SM_STAGE_DATE   DATE,
  COMPONENT_NUM   VARCHAR2(40 BYTE),
  COMPONENT_TYPE  VARCHAR2(40 BYTE),
  COMPONENT_CODE  VARCHAR2(60)
);


CREATE TABLE XXVS.SM_COMP_OBJECTS
(
  ID         NUMBER                             NOT NULL PRIMARY KEY ,
  COMP_ID    NUMBER,
  OBJECT_ID  NUMBER,
  LINK_TYPE  VARCHAR2(40 BYTE)
);

CREATE TABLE XXVS.SM_ENVIRONMENTS
(
  ID        NUMBER                              NOT NULL PRIMARY KEY,
  NAME      VARCHAR2(80 BYTE)                   NOT NULL,
  ENV_HOST  VARCHAR2(160 BYTE),
  ENV_URL   VARCHAR2(160 BYTE),
  ENV_DB    VARCHAR2(160 BYTE),
  ENV_USER  VARCHAR2(80 BYTE),
  ENV_PASS  VARCHAR2(80 BYTE)
);

CREATE TABLE XXVS.SM_OBJECTS
(
  ID             NUMBER                         NOT NULL primary key ,
  CODE           VARCHAR2(50) NOT NULL,
  NAME           VARCHAR2(300 BYTE),
  OBJECT_TYPE    VARCHAR2(50 BYTE),
  OBJECT_SOURCE  VARCHAR2(300 BYTE)
);

CREATE TABLE XXVS.SYS_LISTS
(
  ID    NUMBER                                  NOT NULL PRIMARY KEY ,
  NAME  VARCHAR2(40 BYTE),
  TYPE  VARCHAR2(20 BYTE),
  SQL   VARCHAR2(2000 BYTE)
);

CREATE TABLE XXVS.SYS_LIST_VALUES
(
  ID             NUMBER                         NOT NULL PRIMARY KEY,
  LIST_ID        NUMBER                         NOT NULL,
  CODE           VARCHAR2(40 BYTE),
  VALUE          VARCHAR2(300 BYTE),
  VALUE_SEQ      NUMBER
);

CREATE TABLE XXVS.SYS_MAPPINGS
(
  ID             NUMBER                         NOT NULL PRIMARY KEY,
  MAPPING_TYPE   VARCHAR2(50)                         NOT NULL,
  KEY1            VARCHAR2(50)                         NOT NULL,
  KEY2            VARCHAR2(50)                         ,
  KEY3            VARCHAR2(50)                         ,
  KEY4            VARCHAR2(50)                         ,
  VALUE1          VARCHAR2(300)                       NOT NULL,
  VALUE2          VARCHAR2(300)                       ,
  VALUE3          VARCHAR2(300)                       ,
  VALUE4          VARCHAR2(300)
);

CREATE OR REPLACE SYNONYM APPS.OA_MENUS FOR XXVS.OA_MENUS;


CREATE OR REPLACE SYNONYM APPS.OA_MENU_ITEMS FOR XXVS.OA_MENU_ITEMS;


CREATE OR REPLACE SYNONYM APPS.SM_COMPONENTS FOR XXVS.SM_COMPONENTS;


CREATE OR REPLACE SYNONYM APPS.SM_COMP_OBJECTS FOR XXVS.SM_COMP_OBJECTS;


CREATE OR REPLACE SYNONYM APPS.SM_ENVIRONMENTS FOR XXVS.SM_ENVIRONMENTS;


CREATE OR REPLACE SYNONYM APPS.SM_OBJECTS FOR XXVS.SM_OBJECTS;


CREATE OR REPLACE SYNONYM APPS.SYS_LISTS FOR XXVS.SYS_LISTS;


CREATE OR REPLACE SYNONYM APPS.SYS_LIST_VALUES FOR XXVS.SYS_LIST_VALUES;

CREATE OR REPLACE SYNONYM APPS.SYS_MAPPINGS FOR XXVS.SYS_MAPPINGS;


DROP SEQUENCE APPS.SM_COMPONENT_S;
DROP SEQUENCE APPS.SM_COMP_OBJECT_S;
DROP  SEQUENCE APPS.SM_OBJECT_S;
DROP  SEQUENCE APPS.OA_MENU_ITEM_S;
DROP  SEQUENCE APPS.OA_MENU_S;
DROP  SEQUENCE APPS.OA_REGION_S;
DROP  SEQUENCE APPS.SYS_LIST_S;
DROP  SEQUENCE APPS.SYS_LIST_VALUE_S;
DROP  SEQUENCE APPS.SYS_MAPPING_S;
DROP  SEQUENCE APPS.XXOA_DEBUG_S;


CREATE SEQUENCE APPS.SM_COMPONENT_S;
CREATE SEQUENCE APPS.SM_COMP_OBJECT_S;
CREATE SEQUENCE APPS.SM_OBJECT_S;
CREATE SEQUENCE APPS.OA_MENU_ITEM_S;
CREATE SEQUENCE APPS.OA_MENU_S;
CREATE SEQUENCE APPS.OA_REGION_S;
CREATE SEQUENCE APPS.SYS_LIST_S;
CREATE SEQUENCE APPS.SYS_LIST_VALUE_S;
CREATE SEQUENCE APPS.SYS_MAPPING_S;
CREATE SEQUENCE APPS.XXOA_DEBUG_S;

CREATE UNIQUE INDEX XXVS.SYS_LISTS_UI1 ON XXVS.SYS_LISTS(NAME);
CREATE UNIQUE INDEX XXVS.SYS_LIST_VALUES_UI1 ON XXVS.SYS_LIST_VALUES(LIST_ID, CODE);